# Price Collar Usage

In [26]:
import pandas as pd
import numpy as np

df = pd.read_csv("price_collar_usage.csv")
df

,sym,lastPublish,age,ticking,tradable,bid,ask,refPrice
0,AUDCAD,NaN,1705,1,1,0.866770,0.883785,0.900
1,AUDCHF,NaN,1726,1,1,0.604250,0.605450,0.580
2,AUDJPY,NaN,1603,1,1,67.515360,68.039540,64.000
3,AUDNZD,NaN,2105,1,1,1.031537,1.045268,1.085
4,AUDUSD,NaN,1712,1,1,0.618248,0.626657,0.585

## Add min bid / max ask using ref price

Set a percentage of ref price to be used to generate collar

In [21]:
percent_use = 0.5

In [27]:
df["bidMin"] = df["refPrice"]*(1-percent_use)
df["askMax"] = df["refPrice"]*(1+percent_use)
df

,sym,lastPublish,age,ticking,tradable,bid,ask,refPrice,bidMin,askMax
0,AUDCAD,NaN,1705,1,1,0.866770,0.883785,0.900,0.4500,1.3500
1,AUDCHF,NaN,1726,1,1,0.604250,0.605450,0.580,0.2900,0.8700
2,AUDJPY,NaN,1603,1,1,67.515360,68.039540,64.000,32.0000,96.0000
3,AUDNZD,NaN,2105,1,1,1.031537,1.045268,1.085,0.5425,1.6275
4,AUDUSD,NaN,1712,1,1,0.618248,0.626657,0.585,0.2925,0.8775

In [28]:
df["bidPCUsage"] = 100 * np.minimum(1, np.maximum(0, (df["refPrice"]-df["bid"])/(df["refPrice"]-df["bidMin"])))
df["askPCUsage"] = 100 * np.minimum(1, np.maximum(0, (df["ask"]-df["refPrice"])/(df["askMax"]-df["refPrice"])))
#df["bidPricesRatio"] = (df["refPrice"]-df["bid"])/(df["refPrice"]-df["bidMin"])
#df["askPricesRatio"] = (df["ask"]-df["refPrice"])/(df["askMax"]-df["refPrice"])
df

,sym,lastPublish,age,ticking,tradable,bid,ask,refPrice,bidMin,askMax,bidPCUsage,askPCUsage
0,AUDCAD,NaN,1705,1,1,0.866770,0.883785,0.900,0.4500,1.3500,7.384444,0.000000
1,AUDCHF,NaN,1726,1,1,0.604250,0.605450,0.580,0.2900,0.8700,0.000000,8.775862
2,AUDJPY,NaN,1603,1,1,67.515360,68.039540,64.000,32.0000,96.0000,0.000000,12.623563
3,AUDNZD,NaN,2105,1,1,1.031537,1.045268,1.085,0.5425,1.6275,9.854931,0.000000
4,AUDUSD,NaN,1712,1,1,0.618248,0.626657,0.585,0.2925,0.8775,0.000000,14.241607